#!/bin/bash

type brew >/dev/null 2>&1 || {
  echo Installing Homebrew...
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

for brewfile in $(ls Brewfile*); do
  echo Installing from Brewfile ${brewfile}
  brew bundle --file=${brewfile}
done
