#!/usr/bin/env bash

###############################################################################
# System Config                                                               #
###############################################################################

echo Setting system Dark theme...

osascript <<EOD
tell application "System Preferences"
  activate
  set the current pane to pane id "com.apple.preference.general"
end tell
tell application "System Events" to tell process "System Preferences"
  delay 1
  set cb to checkbox "Dark" of window "General"
  if not (value of cb as boolean) then
    click cb
  end if
end tell
tell application "System Preferences"
  quit
end tell
EOD

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Disable the "Are you sure you want to open this application?" dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Reveal IP address, hostname, OS version, etc. when clicking the clock
# in the login window
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostNameuu

# Enable full keyboard access for all controls
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Set the timezone; see `sudo systemsetup -listtimezones` for other values
sudo systemsetup -settimezone "America/New_York" > /dev/null

###############################################################################
# Finder                                                                      #
###############################################################################

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

###############################################################################
# Spotlight                                                                   #
###############################################################################

# Set spotlight search prefs
defaults write com.apple.spotlight orderedItems -array \
  '{ "enabled" = 1; "name" = "APPLICATIONS"; }' \
  '{ "enabled" = 0; "name" = "MENU_SPOTLIGHT_SUGGESTIONS"; }' \
  '{ "enabled" = 0; "name" = "MENU_CONVERSION"; }' \
  '{ "enabled" = 1; "name" = "MENU_EXPRESSION"; }' \
  '{ "enabled" = 1; "name" = "MENU_DEFINITION"; }' \
  '{ "enabled" = 1; "name" = "SYSTEM_PREFS"; }' \
  '{ "enabled" = 0; "name" = "DOCUMENTS"; }' \
  '{ "enabled" = 1; "name" = "DIRECTORIES"; }' \
  '{ "enabled" = 0; "name" = "PRESENTATIONS"; }' \
  '{ "enabled" = 0; "name" = "SPREADSHEETS"; }' \
  '{ "enabled" = 0; "name" = "PDF"; }' \
  '{ "enabled" = 0; "name" = "MESSAGES"; }' \
  '{ "enabled" = 0; "name" = "CONTACT"; }' \
  '{ "enabled" = 0; "name" = "EVENT_TODO"; }' \
  '{ "enabled" = 0; "name" = "IMAGES"; }' \
  '{ "enabled" = 0; "name" = "BOOKMARKS"; }' \
  '{ "enabled" = 0; "name" = "MUSIC"; }' \
  '{ "enabled" = 0; "name" = "MOVIES"; }' \
  '{ "enabled" = 0; "name" = "FONTS"; }' \
  '{ "enabled" = 0; "name" = "MENU_OTHER"; }' \
  '{ "enabled" = 1; "name" = "SOURCE"; }'

# Load new settings before rebuilding the index
killall mds > /dev/null 2>&1
# Make sure indexing is enabled for the main volume
sudo mdutil -i on / > /dev/null
# Rebuild the index from scratch
sudo mdutil -E / > /dev/null

###############################################################################
# Display                                                                     #
###############################################################################

# Enable subpixel font rendering on non-Apple LCDs
# Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
# Note: Logout or restart required in order to apply changes
# Note: The System Preferences smoothing checkbox was removed in Big Sur
defaults write NSGlobalDomain AppleFontSmoothing -int 1

###############################################################################
# Dock                                                                        #
###############################################################################

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don't use
# the Dock to launch apps.
defaults write com.apple.dock persistent-apps -array

# Show only open applications in the Dock
defaults write com.apple.dock static-only -bool true

# Don't automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

##############################################################################
# Miscellaneous                                                              #
##############################################################################

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0
# Open and save files as UTF-8 in TextEdit
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

# Enable the debug menu in Disk Utility
defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true
defaults write com.apple.DiskUtility advanced-image-options -bool true

# Auto-play videos when opened with QuickTime Player
defaults write com.apple.QuickTimePlayerX MGPlayMovieOnOpen -bool true

# Enable repeat keypresses for VS Code
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

##############################################################################
# Kill/restart affected applications                                         #
##############################################################################

echo Restarting configured apps...

for app in "Activity Monitor" \
  "Dock" \
  "Finder"\
  "Spotlight"; do
  killall "${app}" &> /dev/null
done
echo Done.
